Tracker.WebMVC/Controllers/LogController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Dynamic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tracker.Services;

namespace Tracker.WebMVC.Controllers
{
    [Authorize]
    public class LogController : Controller
    {
        // GET: Log
        public ActionResult Index()
        {
            dynamic logView = new ExpandoObject();
            var serviceCycle = CreateTrackerServiceCycle();
            var serviceBBT = CreateTrackerServiceBBT();
            logView.Cycle = serviceCycle.ViewAllCycles();
            logView.BBT = serviceBBT.ViewAllBBTs();
            return View(logView);
        }
        public ActionResult GoToViews()
        {
            return View();
        }
        private CycleService CreateTrackerServiceCycle()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new CycleService(userID);
            return service;
        }
        private BBTService CreateTrackerServiceBBT()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new BBTService(userID);
            return service;
        }

    }
}

Tracker.WebMVC/Controllers/PersonalInfoController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Tracker.Models.PersonalInfoModels;
using Tracker.Services;

namespace Tracker.WebMVC.Controllers
{
    [Authorize]
    public class PersonalInfoController : Controller
    {
        // GET: PersonalInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult PersonalInfoCreate()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalInfoCreate(PersonalInfoCreate model)
        {
            if (!ModelState.IsValid) return View(model);

            var service = CreateTrackerService();
            var userID = User.Identity.GetUserId();

            if (service.CreatePersonalInfo(model))
            {
                TempData["SaveResult"] = "Your note was created.";
                return RedirectToAction("PersonalInfoDetails", "PersonalInfo", new { id = userID });
            }
            ModelState.AddModelError("", "Personal Information could not be added.");
            return View(model);

        }
        public ActionResult PersonalInfoDetails()
        {
            var svc = CreateTrackerService();

            var model = svc.GetPersonalInfoByID(Guid.Parse(User.Identity.GetUserId()));
            if (model != null)
            {
                return View(model);
            }
            else
            {
                return RedirectToAction("PersonalInfoCreate", "PersonalInfo");
            }
        }

        public ActionResult PersonalInfoEdit(Guid id)
        {
            var service = CreateTrackerService();
            var detail = service.GetPersonalInfoByID(id);
            var model = new PersonalInfoUpdate
            {
                UserId = id,
                FirstName = detail.FirstName,
                LastName = detail.LastName,
                Age = detail.Age,
                PreviousPregnancies = detail.PreviousPregnancies,
                ViablePreg = detail.ViablePreg,
                FailedPreg = detail.FailedPreg,
                TerminatedPreg = detail.TerminatedPreg,
                WhyUsing = detail.WhyUsing,
                MedicalHistory = detail.MedicalHistory,
                ModifiedTime = DateTimeOffset.Now
            };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalInfoEdit(Guid id, PersonalInfoUpdate model)
        {
            var userID = User.Identity.GetUserId();
            if (!ModelState.IsValid) return View(model);
            if (model.UserId != id)
            {
                ModelState.AddModelError("", "ID Mismatch");
                return View(model);
            }
            var service = CreateTrackerService();
            if (service.UpdatePersonalInfo(model))
            {
                TempData["SaveResult"] = "Your personal information has been updated.";
                return RedirectToAction("PersonalInfoDetails", "PersonalInfo", new { id = id });
            }
            ModelState.AddModelError("", "Your personal information could not be updated.");
            return View(model);
        }
        public ActionResult Delete(Guid id)
        {
            var svc = CreateTrackerService();
            var model = svc.GetPersonalInfoByID(id);
            return View(model);
            //return RedirectToAction("PersonalInfoDelete", "PersonalInfo", new { id = id });
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult PersonalInfoDelete(Guid id)
        {
            var service = CreateTrackerService();
            service.DeletePersonalInfo(id);
            TempData["SaveResult"] = "Your personal information was deleted.";
            return RedirectToAction("PersonalInfoCreate", "PersonalInfo");
        }

        private PersonalInfoService CreateTrackerService()
        {
            var userId = Guid.Parse(User.Identity.GetUserId());
            var service = new PersonalInfoService(userId);
            return service;
        }
    }
}

Tracker.WebMVC/Views/PersonalInfo/Delete.cshtml
@model Tracker.Models.PersonalInfoModels.PersonalInfoDetails

@{
    ViewBag.Title = "PersonalInfoDelete";
}

<h2>PersonalInfoDelete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>PersonalInfoDetails</h4>
    <hr />
    <dl class="dl-horizontal">
        
        <dt>
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FirstName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.LastName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.LastName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Age)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Age)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.PreviousPregnancies)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PreviousPregnancies)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ViablePreg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ViablePreg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.FailedPreg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FailedPreg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.TerminatedPreg)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.TerminatedPreg)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MedicalHistory)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MedicalHistory)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

Tracker.WebMVC/Views/PersonalInfo/PersonalInfoCreate.cshtml
@model Tracker.Models.PersonalInfoModels.PersonalInfoCreate

@{
    ViewBag.Title = "PersonalInfoCreate";
}
    <div class="personal-info-create">
        <h2>Personal Infomation</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Enter Personal Information</h4>
        <hr />
        <div class="personal-info-create-table">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PreviousPregnancies, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PreviousPregnancies)
                        @Html.ValidationMessageFor(model => model.PreviousPregnancies, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ViablePreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ViablePreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ViablePreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FailedPreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FailedPreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FailedPreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TerminatedPreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TerminatedPreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TerminatedPreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MedicalHistory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MedicalHistory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MedicalHistory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Create" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("View Personal Information", "PersonalInfoDetails", new { })
        </div>
    </div>


@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

Tracker.WebMVC/Views/PersonalInfo/PersonalInfoDetails.cshtml
@model Tracker.Models.PersonalInfoModels.PersonalInfoDetails

@{
    ViewBag.Title = "PersonalInfoDetails";
}

    <div class="personal-info-details">
        <h2>Personal Information</h2>

        <div>
            @Html.HiddenFor(model => model.UserID)

            <h4>Details</h4>
            <br />

            <hr />
            <div class="personal-info-details-table">
                <dl class="dl-horizontal">
                    <dt>
                        @Html.DisplayNameFor(model => model.FirstName)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.FirstName)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.LastName)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.LastName)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.Age)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.Age)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.PreviousPregnancies)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.PreviousPregnancies)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ViablePreg)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.ViablePreg)
                        </span>
                    </dd>
                @*</dl>
                <dl>*@
                    <dt>
                        @Html.DisplayNameFor(model => model.FailedPreg)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.FailedPreg)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.TerminatedPreg)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.TerminatedPreg)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.MedicalHistory)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.MedicalHistory)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.CreatedTime)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.CreatedTime)
                        </span>
                    </dd>

                    <dt>
                        @Html.DisplayNameFor(model => model.ModifiedTime)
                    </dt>

                    <dd>
                        <span>
                            @Html.DisplayFor(model => model.ModifiedTime)
                        </span>
                    </dd>

                </dl>
            </div>
        </div>
        <p>
            <div class="btn btn-default" id="edit-from-personal-info-details">
                @Html.ActionLink("Edit", "PersonalInfoEdit", new { id = Model.UserID })
            </div>
            @*@Html.ActionLink("Delete", "Delete", new { id = Model.UserID })*@
            <div class="btn btn-default" id="go-to-log-from-personal-info-details">
                @Html.ActionLink("Go To Log", "Index", "Log")
            </div>

        </p>
    </div>

Tracker.WebMVC/Views/PersonalInfo/PersonalInfoEdit.cshtml
@model Tracker.Models.PersonalInfoModels.PersonalInfoUpdate

@{
    ViewBag.Title = "PersonalInfoEdit";
}

    <div class="personal-info-edit">
        <h2>Personal Information</h2>


        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Update Personal Information</h4>
        <hr />
        <div class="personal-info-edit-table">
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.UserId)

            <div class="form-group">
                @Html.LabelFor(model => model.FirstName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FirstName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Age, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Age, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.Age, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PreviousPregnancies, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    <div class="checkbox">
                        @Html.EditorFor(model => model.PreviousPregnancies)
                        @Html.ValidationMessageFor(model => model.PreviousPregnancies, "", new { @class = "text-danger" })
                    </div>
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.ViablePreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.ViablePreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.ViablePreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.FailedPreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FailedPreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.FailedPreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.TerminatedPreg, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.TerminatedPreg, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.TerminatedPreg, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.MedicalHistory, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.MedicalHistory, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.MedicalHistory, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-default" />
                </div>
            </div>
        </div>
    </div>
        }

        <div>
            @Html.ActionLink("Back to Personal Information", "PersonalInfoDetails", new { id = Model.UserId })
        </div>
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}